version: '2'

services:
  powerdns-authoritative:
    image: interlegis/powerdns:4.0.1-1
    hostname: powerdns-authoritative
    depends_on:
      - powerdns-authoritative-mysql
    links:
      - powerdns-authoritative-mysql:mysql
    ports:
      - 53:53
      - 53:53/udp
      - 8081:8081
    environment:
      - PDNSCONF_API_KEY=my_awesome_API-123
      - PDNSCONF_MASTER=yes
      - PDNSCONF_DEFAULT_SOA_NAME=ns-awesome.sawbuck.com
      - MYSQL_ENV_MYSQL_DATABASE=pdns
      - MYSQL_ENV_MYSQL_USER=pdns
      - MYSQL_ENV_MYSQL_PASSWORD=pdnspw

  powerdns-authoritative-mysql:
    image: mariadb
    hostname: powerdns-authoritative-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpw
      - MYSQL_DATABASE=pdns
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD=pdnspw

  powerdns-admin:
    image: powerdns-admin
    hostname: powerdns-admin
    depends_on:
      - powerdns-admin-mysql
      - powerdns-authoritative
    links:
      - powerdns-admin-mysql:mysql
      - powerdns-authoritative:powerdns-server
    volumes:
      - /Users/yury/powerdns-with-admin/PowerDNS-Admin:/home/web/powerdns-admin
    ports:
      - 9393:9393
    environment:
      - WAITFOR_DB=60

  powerdns-admin-mysql:
    image: mariadb
    hostname: powerdns-admin-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpw
      - MYSQL_DATABASE=powerdns-admin
      - MYSQL_USER=powerdns-admin
      - MYSQL_PASSWORD=powerdns-adminpw